name: Cache Deploy
on:
  push:
    branches:
    - 'master'
    - 'actions/cache'

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISABLE_NOTIFIER: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Compile CSS
        run: npm run styles

      - name: Compile JavaScript
        run: npm run scripts

      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          rm .gitignore
          mv .gitignore-build .gitignore
          git add -A
          git commit -m "Build"

          # Setup variables
          BUILD_BRANCH="${GITHUB_REF_NAME}-build"
          GITHUB_ACTION_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks"

          # Switch branches... maybe?
          git fetch --all
          if [ ! `git branch -r --list origin/$BUILD_BRANCH` ]; then
            # Branch doesn't exist. Create it and check it out.
            git checkout --orphan ${BUILD_BRANCH}
            git rm -rf .
            git commit --allow-empty -m "Initial Commit"
          else
            git checkout -f ${BUILD_BRANCH}
          fi

          # Capture diff of the changes between the two branches
          git diff --no-color --binary ${BUILD_BRANCH} ${GITHUB_REF_NAME} > ~/${BUILD_BRANCH}.diff

          # If the diff file is not empty then continue
          if [ -s ~/${BUILD_BRANCH}.diff ]; then
            # Apply changes to the build branch
            git apply ~/${BUILD_BRANCH}.diff

            # Add file changes and commit
            git add .
            git commit -m "Merged ${GITHUB_SHA} from ${GITHUB_REF_NAME}" -m "${GITHUB_ACTION_URL}"
            git push origin ${BUILD_BRANCH} --force
          else
            echo "Nothing changed. No commit."
          fi

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

#      - name: Setup tmate session (failure)
#        uses: mxschmitt/action-tmate@v3
#        if: ${{ failure() }}
